server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: sample_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: sample_logs
          __path__: /var/log/sample.log
    pipeline_stages:
      - json:
          expressions:
            observed_timestamp_rfc3339: observed_timestamp_rfc3339
            instrumentation_scope: instrumentation_scope
            severity_text: severity_text
            body: body
      - timestamp:
          source: observed_timestamp_rfc3339
          format: RFC3339
      - labels:
          instrumentation_scope:
          severity_text: