name: Deploy Monitoring Stack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
      
      - name: Copy configuration files
        run: |
          scp -r docker-compose.yml loki-config.yaml promtail-config.yaml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/ubuntu/Grafana_Configs/
      
      - name: Deploy stack
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} '
            cd /home/ubuntu/Grafana_Configs
            docker-compose down
            docker-compose pull
            docker-compose up -d
          '

      - name: Cleanup SSH key
        run: rm -rf ~/.ssh